### ISSUE TITLE
Some modules are needlessly deeply nested

### ISSUE THREAD

**Issue by fmccl** [Adrian8115/bedrock-rs#12]
`bedrock_rs::core::dimension::Dimension` for example, the `core` and `dimension` modules are both redundant, core stuff should be in the root of the crate, and dimension doesn't need it's own module because it's just one enum.

**Comment by Adrian8115** [comment]
I agree that some stuff is unnecessarilly nested, this will/should be fixed with simple reexports in the `lib.rs` file. Thank you for pointing it out!
