### ISSUE TITLE
Cursor<Vec<u8>> in NBT function signatures should be replaced with Box<dyn Read>

### ISSUE THREAD

**Issue by fmccl** [Adrian8115/bedrock-rs#23]
This would only require changes in the NBT crate and minimizes copies, which are necessary to put LevelDB data into `Vec`s:
```rs
let leveldb_bytes: LevelDBManagedBytes = ... // this wrapper struct is necessary to call leveldb_free on Drop, because the 
// memory was allocated in C++

leveldb_bytes.get().to_vec() // to_vec function copies!!!! 
```
Cursor<Vec<u8>> does implement seek so only minimal changes would be needed.

**Comment by fmccl** [comment]
If it used seek I would then be able to use Cursor<&[u8]> which doesn't require a copy

**Comment by Adrian8115** [comment]
so you are saying we should switch the nbt crate over to using `Cursor<&[u8]>` where ` Cursor<Vec<u8>>` has been used prior, for less copying?

**Comment by fmccl** [comment]
No. I think that ByteStreamRead could be replaced like this:
```
pub type ByteStreamRead = Box<dyn Read>; // the box might make you think this is slow because of heap allocation
// but vecs are heap allocated so it doesn't really matter
```
We would only need to change code where `ByteStreamRead`s are created because the interface of dyn Read is the same as a Cursor. In the NBT crate this is only once in the deserialize_vec function which should probably be removed anyway because it can't be used without copying.

Like that, you are still able to use a `Vec` if it is convenient but you can also use a `&[u8]`:
```
let y: ByteStreamRead = Box::new(Cursor::new(b"abc")); // b"abc" is &[u8; 3]
let x: ByteStreamRead = Box::new(Cursor::new(Vec::new()));
```

**Comment by fmccl** [comment]
I hadn't got everything worked out yet when I made this issue sorry if it's confusing

**Comment by Adrian8115** [comment]
This should be fixed by the prior mentioned pull request
